---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.0.2.15"}]
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04 

suites:
  - name: default
    data_bags_path: "../../data_bags"
    run_list:
      - recipe[lamp::default]
    provisioner:
      encrypted_data_bag_secret_key_path: /tmp/encrypted_data_bag_secret
    attributes:
      lamp:
        passwords:
          secret_path: '/tmp/kitchen/encrypted_data_bag_secret'
