name 'lamp'
maintainer 'Daniel T.'
maintainer_email 'daniel@localhost'
license 'all_rights'
description 'Installs/Configures LAMP stack'
long_description 'Installs/Configures LAMP stack'
version '0.4.0'


depends 'apt', '~> 2.6.1'
depends 'httpd', '~> 0.2.14'
depends 'firewall', '~> 1.5.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.17'
depends 'database', '~> 4.0.3'
